# Generated by Django 4.2 on 2023-05-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfil',
            table=None,
        ),
    ]
