# Generated by Django 4.2 on 2023-06-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0011_alter_tareas_fterminada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300, verbose_name='comentario')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_tarea', to='tareas.tareas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentarios',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-id'],
            },
        ),
    ]
