# Generated by Django 4.2 on 2023-06-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['id'], 'verbose_name': 'Comentarios', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
