# Generated by Django 4.2 on 2023-05-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_Status',
            new_name='Status',
        ),
    ]
