# Generated by Django 4.2 on 2023-05-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_rename_t_status_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['-id'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
