# Generated by Django 4.2 on 2023-05-18 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0004_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='CreadaPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_tarea', to=settings.AUTH_USER_MODEL),
        ),
    ]
