# Generated by Django 4.2 on 2023-05-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_tareas_creadapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Ffinal',
            field=models.DateField(),
        ),
    ]
