# Generated by Django 4.2 on 2023-05-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_tareas_ffinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
    ]
