# Generated by Django 4.2 on 2023-05-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_tareas_porcentaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='Asignada',
            new_name='asignada',
        ),
    ]
