# Generated by Django 4.2 on 2023-05-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_rename_asignada_tareas_asignada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='asignada',
            new_name='user',
        ),
    ]
