# Generated by Django 4.2 on 2023-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_tareas_fterminada_alter_tareas_ffinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Fterminada',
            field=models.DateField(blank=True, help_text='fecha final', null=True),
        ),
    ]
