# Generated by Django 4.2 on 2023-06-18 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0011_alter_tareas_fterminada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=150, verbose_name='archivo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion')),
                ('porcentaje', models.IntegerField(default=0)),
                ('Fcreacion', models.DateTimeField(auto_now_add=True)),
                ('Ffinal', models.DateField(help_text='fecha plazo')),
                ('Fterminada', models.DateField(blank=True, help_text='fecha final', null=True)),
                ('calificaon', models.IntegerField(blank=True, help_text='Calificación del la tarea', null=True)),
                ('CreadaPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_archivo', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_archivo', to='categorias.categorias')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridad_archivo', to='tareas.prioridad')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_archivo', to='tareas.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_archivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ArchivoTarea',
                'verbose_name_plural': 'ArchivoTareas',
                'ordering': ['-id'],
            },
        ),
    ]
