# Generated by Django 4.2 on 2023-06-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_archivotareas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivotareas',
            old_name='calificaon',
            new_name='calificacion',
        ),
    ]
